resources:
- variables:
    solution: 'src/calmo.framework.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Debug'

jobs:
  - job: Phase_1
    pool:
      vmImage: 'VS2017-Win2016'
    displayName: 'Build default .NET Solution'
    condition: succeeded()
    steps:
    - task: NuGetToolInstaller@0

    - task: NuGetCommand@2
      inputs:
        command: restore
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: VSTest@2
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
