//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calmo.Data.Sharepoint.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Calmo.Data.Sharepoint.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensão de arquivo inválida..
        /// </summary>
        internal static string ExtensaoArquivoInvalida {
            get {
                return ResourceManager.GetString("ExtensaoArquivoInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A referência &apos;{0}&apos; (Versão: {1}), não corresponde a nehum arquivo..
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor da coluna &apos;{0}&apos; é do tipo &apos;{1}&apos; e não pode ser atribuído na propriedade &apos;{2}&apos; do tipo &apos;{3}&apos;..
        /// </summary>
        internal static string FillInvalidCast {
            get {
                return ResourceManager.GetString("FillInvalidCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A opção de campos fornecidade &apos;{0}&apos; não corresponde com nenhuma opção válida do enumerador AddFieldOptions, Assembly Microsoft.SharePoint.Client..
        /// </summary>
        internal static string InvalidAddFieldOptions {
            get {
                return ResourceManager.GetString("InvalidAddFieldOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo de campo &apos;{0}&apos; não corresponde com nenhuma opção válida do enumerador FieldType, Assembly Microsoft.SharePoint.Client..
        /// </summary>
        internal static string InvalidFieldType {
            get {
                return ResourceManager.GetString("InvalidFieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O código (&apos;{0}&apos;) do item informado não existe na lixeira..
        /// </summary>
        internal static string InvalidRecycleBinItemId {
            get {
                return ResourceManager.GetString("InvalidRecycleBinItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo &apos;{0}&apos; a ser preenchido é inválido. O tipo deve conter uma propriedade &apos;Id&apos; do tipo &apos;System.Int32&apos;..
        /// </summary>
        internal static string InvalidSharepointType {
            get {
                return ResourceManager.GetString("InvalidSharepointType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A versão do arquivo informada não existe..
        /// </summary>
        internal static string VersaoInexistente {
            get {
                return ResourceManager.GetString("VersaoInexistente", resourceCulture);
            }
        }
    }
}
